### ISSUE TITLE
Impossible to give Mystery Boxes

### ISSUE THREAD

**Issue by Aurelien30000** [yapzhenyie/GadgetsMenu#822]
**Describe the bug**
This issue only occurs with particular conditions, because works on my lobby but not on my other servers where there isn't a mystery box.

Executed **/gmysterybox give Aurelien30000 5 5** then:
```[11:02:09 WARN]: [GadgetsMenu] Plugin GadgetsMenu v4.6.3 generated an exception while executing task 3052
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.utils.mysteryboxes.CosmeticItems.getRandomItem(CosmeticItems.java:69) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.randomGetCosmeticItem(MysteryBoxesManager.java:85) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.item(MysteryBoxesManager.java:80) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.giveMysteryBoxes(MysteryBoxesManager.java:33) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$10(PlayerManager.java:1768) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Thanks :)

**To Reproduce**
1. Try to give yourself mystery boxes without a mystery box in the world, seems to be the source of the issue.

**Expected behavior**
No stacktrace and boxes correctly given.

**Further Information (please complete the following information):**
 - Server Version: 1.16.4
 - GadgetsMenu Version: Premium 4.6.3

**Comment by yapzhenyie** [comment]
@Aurelien30000 Seems to be the issues of Mystery Box loots. You might have disabled all mystery box loots inside the `mysteryboxes.yml` file. Can I have your `config.yml` file & `mysteryboxes.yml` file.

**Comment by Aurelien30000** [comment]
Sure, here are:
[configs.zip](https://github.com/yapzhenyie/GadgetsMenu/files/5730333/configs.zip)

**Comment by yapzhenyie** [comment]
Did you saw any other errors before this error comes out? While gadgetsmenu is loading, any errors in the console?

**Comment by Aurelien30000** [comment]
> Did you saw any other errors before this error comes out? While gadgetsmenu is loading, any errors in the console?

No, plugin is loaded correctly.

**Comment by yapzhenyie** [comment]
> > Did you saw any other errors before this error comes out? While gadgetsmenu is loading, any errors in the console?
> 
> No, plugin is loaded correctly.

can you send me the full log?

**Comment by Aurelien30000** [comment]
The first log is already the full one, here is another and complete log:

```
[15:59:44] [Server thread/INFO]: 【Cosmétiques】➯ Vous avez correctement donné 5 Boîte(s) Mystère(s) à Aurelien30000.
[15:59:44] [Craft Scheduler Thread - 568 - GadgetsMenu/WARN]: [GadgetsMenu] Plugin GadgetsMenu v4.6.3 generated an exception while executing task 3857034
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.utils.mysteryboxes.CosmeticItems.getRandomItem(CosmeticItems.java:69) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.randomGetCosmeticItem(MysteryBoxesManager.java:85) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.item(MysteryBoxesManager.java:80) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.mysteryboxes.MysteryBoxesManager.giveMysteryBoxes(MysteryBoxesManager.java:33) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$10(PlayerManager.java:1768) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by yapzhenyie** [comment]
I need all the GadgetsMenu file. It seems like you have change the cosmetic item rarity and GadgetsMenu cannot find any cosmetic item that is rarity `Rare`

**Comment by Aurelien30000** [comment]
I don't remember that, but nevermind, here is the whole folder, thanks for your help!
[GadgetsMenu.zip](https://github.com/yapzhenyie/GadgetsMenu/files/5743058/GadgetsMenu.zip)

**Comment by yapzhenyie** [comment]
You set `CanBeFound` to `false` for all the cosmetic items which causes the Mystery Box unable to find any cosmetic item that can be found inside Mystery Box.

**Comment by yapzhenyie** [comment]
To solve this problem, change `CanBeFound` to `true` for the files which inside cosmetics folder.
