### ISSUE TITLE
Plugin GadgetsMenu v4.6.7 generated an exception while executing task 14699 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Blueeyestar** [yapzhenyie/GadgetsMenu#845]
Paper: Paper version git-Paper-592 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Gagdet version: 4.6.7

with the users, all gadgets are gone. You can't choose any more, the error keeps repeating itself in the console

whenever a user enters the server, the error is triggered in the console

```
>.... [17:26:21 WARN]: [GadgetsMenu] 
at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$4(PlayerManager.java:1052) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-592]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-592]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-592]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
>.... [17:26:23 INFO]: MiniaturenNick issued server command: /menue
>.... [17:26:23 INFO]: Blueeyestar issued server command: /tp timo04041
>.... [17:26:24 INFO]: [Roulette] The game "Vegas" is being created: 50%
>.... [17:26:24 INFO]: MiniaturenNick issued server command: /gadgetsmenu main
>.... [17:26:26 INFO]: [Roulette] The game "Vegas" is being created: 75%
>.... [17:26:26 INFO]: UUID of player Lunya10 is 3603b62d-30f2-46bd-a8c8-79d06ef15d09
>.... [17:26:26 INFO]: [Roulette] The game "Vegas" is being created: 75%
>.... [17:26:27 INFO]: [Thirst] Adding player Lunya10 with thirst 71
>.... [17:26:27 INFO]: Die Fluggeschwindigkeit von Lunya10 (Online) wurde auf 1.0 gesetzt.
>.... [17:26:27 INFO]: Lunya10 hat Lululand betreten.
>.... [17:26:27 INFO]: Lunya10[/213.182.138.234:53640] logged in with entity id 4137 at ([world]3349.208328768921, 71.0625, 3844.3374172279973)
>.... [17:26:27 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
>.... [17:26:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
>.... [17:26:27 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
>.... [17:26:27 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.first(ResultSetImpl.java:603)
>.... [17:26:27 WARN]: at com.yapzhenyie.GadgetsMenu.database.mysql.MySQLUtils.initPlayerStats(MySQLUtils.java:63)
>.... [17:26:27 WARN]: at com.yapzhenyie.GadgetsMenu.player.GPlayer.initPlayer(GPlayer.java:91)
>.... [17:26:27 WARN]: at com.yapzhenyie.GadgetsMenu.listeners.PlayerListener.lambda$0(PlayerListener.java:35)
>.... [17:26:27 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
>.... [17:26:27 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [17:26:27 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [17:26:27 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [17:26:27 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [17:26:27 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [17:26:28 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
>.... [17:26:28 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
>.... [17:26:28 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
>.... [17:26:28 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.first(ResultSetImpl.java:603)
>.... [17:26:28 WARN]: at com.yapzhenyie.GadgetsMenu.database.mysql.MySQLUtils.lambda$16(MySQLUtils.java:986)
>.... [17:26:28 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
>.... [17:26:28 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [17:26:28 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [17:26:28 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [17:26:28 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [17:26:28 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [17:26:28 INFO]: [DiscordSRV] Chat: [D] weick68 : Hi
>.... [17:26:29 INFO]: timo04041 issued server command: /gadgetsmenu
>.... [17:26:29 WARN]: [GadgetsMenu] Plugin GadgetsMenu v4.6.7 generated an exception while executing task 23219
java.lang.NullPointerException: null
at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$4(PlayerManager.java:1052) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-592]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-592]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-592]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by yapzhenyie** [comment]
This issue will be fixed in the next update.

**Comment by Blueeyestar** [comment]
that's really great, the users are sad because it no longer works

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.

**Comment by yapzhenyie** [comment]
> that's really great, the users are sad because it no longer works

Check for new update. :D
