### ISSUE TITLE
Can't connect to MySQL Database

### ISSUE THREAD

**Issue by StefanRial** [yapzhenyie/GadgetsMenu#848]
I'm running a Debian 10 server with MariaDB
Java 11, paper 584

I've set up a database "gadgetsmenu" and a user "gadgetsmenu" with full access to the database.
My Gadgetsmenu Config:

```
Player-Data:
  Storage: mysql
  MySQL:
    hostname: localhost
    username: gadgetsmenu
    database: gadgetsmenu
    port: '3306'
    password: (my password)
    useSSL: false
```

When starting the server, I get this error from GadgetsMenu:

```
[GadgetsMenu] Enabling GadgetsMenu v4.6.9
[GadgetsMenu] ------------------------------------------------------
[GadgetsMenu]       GadgetsMenu [Premium] 4.6.9 is loading...
[GadgetsMenu]          [server: git-Paper-584 (MC: 1.16.5)]
[GadgetsMenu]                Plugin by Yap Zhen Yie.
[GadgetsMenu]              Date Modified: 16 April 2021
[GadgetsMenu]
[GadgetsMenu]              Initializing module v1_16_R3
[GadgetsMenu] ------------------------------------------------------
[GadgetsMenu] Connecting to MySQL database...
[GadgetsMenu] --------------------------------------------------
[GadgetsMenu] Failed to connect to MySQL database!
[GadgetsMenu] --------------------------------------------------

java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:315)
at com.yapzhenyie.GadgetsMenu.database.mysql.MySQLConnection.openConnection(MySQLConnection.java:42)
at com.yapzhenyie.GadgetsMenu.database.mysql.MySQLManager.init(MySQLManager.java:69)
at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:352)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580)
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280)
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055)
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
at java.base/java.lang.Thread.run(Thread.java:834)

[GadgetsMenu] Disabling GadgetsMenu v4.6.9
```

**Comment by yapzhenyie** [comment]
@StefanRial Update to the latest paper build
