### ISSUE TITLE
Mystery Boxes placeholder broke

### ISSUE THREAD

**Issue by ResoluteWears** [yapzhenyie/GadgetsMenu#926]
**Mystery Boxes Placeholder in Gadgets Menu**
I seem to have a broken placeholder, even with ProtocolLib updated and Placeholder.

Seems to be {MYSTERY_BOXES} nothing was changed in the config that contains that placeholder.
I asked around my community, and another person has the same plugin (Paid), and he doesn't have an issue..?

![2022-07-25_17 32 18](https://user-images.githubusercontent.com/110077614/181152504-385a9ca5-d101-4498-b14f-df63de996417.png)

**Comment by yapzhenyie** [comment]
Did you get any errors in the console?

**Comment by yapzhenyie** [comment]
Can you provide additional information:

Server version: x.x.x
GadgetsMenu version: x.x.x
ProtocolLib version: x.x.x

**Comment by ResoluteWears** [comment]
Only error I can see is 

`[03:19:36 ERROR]: [GadgetsMenu] Unhandled exception number 2048 occurred in onPacketSending(PacketEvent) for GadgetsMenu
java.lang.IllegalArgumentException: handle (WrappedChatComponent[json={"extra":[{"bold":false,"color":"white","italic":false,"obfuscated":false,"strikethrough":false,"text":"{MYSTERY_BOXES} Available","underlined":false},{"color":"green","italic":false,"text":""}],"text":""}]) is not a interface net.minecraft.network.chat.IChatBaseComponent, but class com.comphenix.protocol.wrappers.WrappedChatComponent
        at com.comphenix.protocol.wrappers.AbstractWrapper.setHandle(AbstractWrapper.java:31) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedChatComponent.<init>(WrappedChatComponent.java:75) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedChatComponent.fromHandle(WrappedChatComponent.java:85) ~[ProtocolLib.jar:?]
        at com.yapzhenyie.GadgetsMenu.hook.protocollib.packets.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:199) ~[Gadgets.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
        at com.denizenscript.denizen.nms.v1_19.impl.network.handlers.DenizenNetworkManagerImpl.a(DenizenNetworkManagerImpl.java:316) ~[Denizen.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2073) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2059) ~[?:?]
        at com.denizenscript.denizen.nms.v1_19.impl.network.handlers.AbstractListenerPlayInImpl.a(AbstractListenerPlayInImpl.java:117) ~[Denizen.jar:?]
        at com.denizenscript.denizen.nms.v1_19.impl.network.handlers.DenizenPacketListenerImpl.a(DenizenPacketListenerImpl.java:127) ~[Denizen.jar:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.broadcast(ChunkMap.java:2341) ~[?:?]
        at net.minecraft.server.level.ServerEntity.broadcastAndSend(ServerEntity.java:390) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:363) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:198) ~[?:?]
        at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:2101) ~[paper-1.19.jar:git-Paper-78]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:2112) ~[paper-1.19.jar:git-Paper-78]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1077) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:908) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:647) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552) ~[paper-1.19.jar:git-Paper-78]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-78]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-78]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by ResoluteWears** [comment]
> Can you provide additional information: Server version: x.x.x GadgetsMenu version: x.x.x ProtocolLib version: x.x.x

Server Version : 1.19
GadgetsMenu Version : 5.2.2
PLib Version : 5.0.0-SNAPSHOT-b583

**Comment by yapzhenyie** [comment]
I will update you by tonight. Currently I'm not free.

**Comment by Fuglen** [comment]
I have the same issue, tested with both earlier and newest versions of Paper and plugin as I believed it worked when I tried to update my server to 1.19 recently. I have tried to delete plugin folder and restart with no success.

Server Version : TPaper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
GadgetsMenu Version : 5.2.2 (Premium)
PLib Version : ProtocolLib v5.0.0-SNAPSHOT-b583

Error from console:
```
[19:53:51] [Server thread/ERROR]: [GadgetsMenu] Unhandled exception occurred in onPacketSending(PacketEvent) for GadgetsMenu
java.lang.IllegalArgumentException: handle (WrappedChatComponent[json={"extra":[{"bold":false,"color":"white","italic":false,"obfuscated":false,"strikethrough":false,"text":"{MYSTERY_BOXES} Available","underlined":false},{"color":"red","italic":false,"text":""}],"text":""}]) is not a interface net.minecraft.network.chat.IChatBaseComponent, but class com.comphenix.protocol.wrappers.WrappedChatComponent
	at com.comphenix.protocol.wrappers.AbstractWrapper.setHandle(AbstractWrapper.java:31) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedChatComponent.<init>(WrappedChatComponent.java:75) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedChatComponent.fromHandle(WrappedChatComponent.java:85) ~[ProtocolLib.jar:?]
	at com.yapzhenyie.GadgetsMenu.hook.protocollib.packets.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:199) ~[GadgetsMenu.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:434) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2067) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2053) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.broadcast(ChunkMap.java:2341) ~[?:?]
	at net.minecraft.server.level.ServerEntity.broadcastAndSend(ServerEntity.java:390) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:363) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:198) ~[?:?]
	at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:2101) ~[paper-1.19.jar:git-Paper-6]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:2112) ~[paper-1.19.jar:git-Paper-6]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1077) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:908) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:647) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-6]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-6]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-6]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-6]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-6]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:53:51] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata@5e1fe76a[
    a=340
    b=[net.minecraft.network.syncher.DataWatcher$Item@6b48f268]
  ]
```

```
[20:24:49] [Server thread/ERROR]: [GadgetsMenu] Unhandled exception number 512 occurred in onPacketSending(PacketEvent) for GadgetsMenu
java.lang.IllegalArgumentException: handle (WrappedChatComponent[json={"extra":[{"bold":false,"color":"white","italic":false,"obfuscated":false,"strikethrough":false,"text":"{MYSTERY_BOXES} Available","underlined":false},{"color":"green","italic":false,"text":""}],"text":""}]) is not a interface net.minecraft.network.chat.IChatBaseComponent, but class com.comphenix.protocol.wrappers.WrappedChatComponent
	at com.comphenix.protocol.wrappers.AbstractWrapper.setHandle(AbstractWrapper.java:31) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedChatComponent.<init>(WrappedChatComponent.java:75) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedChatComponent.fromHandle(WrappedChatComponent.java:85) ~[ProtocolLib.jar:?]
	at com.yapzhenyie.GadgetsMenu.hook.protocollib.packets.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:199) ~[GadgetsMenu.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:434) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2073) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2059) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.broadcast(ChunkMap.java:2341) ~[?:?]
	at net.minecraft.server.level.ServerEntity.broadcastAndSend(ServerEntity.java:390) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:363) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:198) ~[?:?]
	at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:2101) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:2112) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1077) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:908) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:647) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

I see the same as OP on the screenshot but also no cosmetics is being displayed.
![Screenshot_5](https://user-images.githubusercontent.com/6181362/181382790-e90faa7c-bc30-4f6b-95e8-3d422d7a9121.png)

**Comment by Fuglen** [comment]
Thank you for letting us know! I was updating a server where morphs are not allowed so I will try without it.

**Comment by CloudeLecaw** [comment]
hope u find a solution soon :)

**Comment by yapzhenyie** [comment]
Yes, I have rectify the issue and found a solution. Now I am doing other
implementation. Once completed I will release the new update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
