### ISSUE TITLE
 Task #69 for GadgetsMenu v4.7.2 generated an exception

### ISSUE THREAD

**Issue by Pixelssquad** [yapzhenyie/GadgetsMenu#929]
[19:47:31 WARN]: Task #69 for GadgetsMenu v4.7.2 generated an exception
java.lang.NoSuchMethodError: 'double net.minecraft.server.level.EntityPlayer.df()'
	at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.armorstand.EntityNMSArmorStand.setLocationNMS(EntityNMSArmorStand.java:243) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.NMSManagerImpl.spawnNMSArmorStand(NMSManagerImpl.java:90) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.utils.mysteryvault.MysteryVault.createHolograms(MysteryVault.java:154) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.tasks.UpdateHolograms.run(UpdateHolograms.java:35) ~[GadgetsMenu.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1491) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**To Reproduce**
after the server is started, this erroe appear infinitely 

**Further Information (please complete the following information):**
 - Server Version: paper 1.19
 - GadgetsMenu Version: v4.7.2
: Plugins (34): aAdvancedPortalsf, aBlockPhysicsEventDetectorf, aCitizensf, aCitizensTextf, aCoreProtectf, aEconomyShopGUIf, aEssentialsf, aEssentialsChatf, aEssentialsDiscordf, aEssentialsSpawnf, cGadgetsMenuf, aGriefPreventionf, aGSitf, aHolographicDisplaysf, aLibsDisguisesf, aLuckPermsf, aMRedstoneDisablef, aMultiverse-Coref, aMultiverse-Inventoriesf, aNexAuthf, aNexEnginef, aPlayerPointsf, aPluginManagerf, aPremiumVanishf, aProtocolLibf, aSentinelf, aSkinsRestorerf, aTrollBossf, aVaultf, avilibf, aVoidGenf, aWITPf, aWorldEditf, aWorldGuard

Hello, i got this error in console. the error appear infinitely when all plugins are loaded and server is started
in game the plugin work without problem.

Regards and excuse for my bad english
Diego

**Comment by yapzhenyie** [comment]
From version 4.7.2 onwards, only support 1.19.1 and no longer support server 1.19

**Comment by Pixelssquad** [comment]
ahhhhhh tnx!
