### ISSUE TITLE
Error with pets

### ISSUE THREAD

**Issue by Incluuu** [yapzhenyie/GadgetsMenu#939]
**Describe the bug**
There is an error when selecting a pet.

**To Reproduce**
1. Go to '/gadgetsmenu main'
2. Click on 'Pets'
3. Select pet

**Expected behavior**
no error

**Further Information (please complete the following information):**
 - Server Version: Purpur 1.19.2 - 1835
 - GadgetsMenu Version: 5.2.8

**Errors on spawn pets with menugadgets**
Could not pass event CreatureSpawnEvent to WorldGuard v7.0.8-beta-01+cbb2ba7
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because the return value of "org.bukkit.entity.EntityType.getName()" is null
	at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:346) ~[Fawe-WorldEdit-Bukkit-2.4.9-SNAPSHOT-297.jar:?]
	at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:271) ~[Fawe-WorldEdit-Bukkit-2.4.9-SNAPSHOT-297.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:395) ~[Fawe-WorldEdit-Bukkit-2.4.9-SNAPSHOT-297.jar:?]
	at com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatureSpawn(WorldGuardEntityListener.java:623) ~[worldguard-bukkit-7.0.8-beta-01-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor324.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1835]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:749) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:654) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1558) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1466) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1461) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:388) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.pets.entity.utils.SpawnUtil.spawn(SpawnUtil.java:55) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.pets.entity.utils.SpawnUtil.spawnEntityPet(SpawnUtil.java:41) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.pets.Pet.<init>(Pet.java:110) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.pets.PetType.equip(PetType.java:546) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipPet(PlayerManager.java:699) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$loadEquippedCosmetics$6(PlayerManager.java:1111) ~[GadgetsMenu.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Could not pass event CreatureSpawnEvent to PlotSquared v6.10.2-Premium
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because the return value of "org.bukkit.entity.EntityType.getName()" is null
	at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:346) ~[Fawe-WorldEdit-Bukkit-2.4.9-SNAPSHOT-297.jar:?]
	at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:271) ~[Fawe-WorldEdit-Bukkit-2.4.9-SNAPSHOT-297.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:395) ~[Fawe-WorldEdit-Bukkit-2.4.9-SNAPSHOT-297.jar:?]
	at com.plotsquared.bukkit.util.BukkitEntityUtil.checkEntity(BukkitEntityUtil.java:340) ~[PlotSquared-Bukkit-6.10.2-Premium.jar:?]
	at com.plotsquared.bukkit.listener.EntityEventListener.creatureSpawnEvent(EntityEventListener.java:204) ~[PlotSquared-Bukkit-6.10.2-Premium.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor84.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1835]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:749) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:654) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1558) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1466) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1461) ~[?:?]
	at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:388) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.pets.entity.utils.SpawnUtil.spawn(SpawnUtil.java:55) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.pets.entity.utils.SpawnUtil.spawnEntityPet(SpawnUtil.java:41) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.pets.Pet.<init>(Pet.java:110) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.pets.PetType.equip(PetType.java:546) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipPet(PlayerManager.java:699) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.lambda$loadEquippedCosmetics$6(PlayerManager.java:1111) ~[GadgetsMenu.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1835]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by yapzhenyie** [comment]
Can you please report this issue to WorldGuard plugin as well?
`Could not pass event CreatureSpawnEvent to WorldGuard v7.0.8-beta-01+cbb2ba7`

**Comment by Incluuu** [comment]
> Can you please report this issue to WorldGuard plugin as well? `Could not pass event CreatureSpawnEvent to WorldGuard v7.0.8-beta-01+cbb2ba7`

The same problem in PlotSquared?
Could not pass event CreatureSpawnEvent to PlotSquared v6.10.2-Premium

Is this error not on the side of menugadgets?

**Comment by yapzhenyie** [comment]
> > Can you please report this issue to WorldGuard plugin as well? `Could not pass event CreatureSpawnEvent to WorldGuard v7.0.8-beta-01+cbb2ba7`
> 
> The same problem in PlotSquared? Could not pass event CreatureSpawnEvent to PlotSquared v6.10.2-Premium
> 
> Is this error not on the side of menugadgets?

Ok, I will check on my side as well.

**Comment by yapzhenyie** [comment]
May I know when you spawning pet, are you standing in a region or PlotSquared area? Can I have your region flag details?

**Comment by yapzhenyie** [comment]
I will do a testing in plots world. Will let you know if the issue is found.

**Comment by Incluuu** [comment]
so?

**Comment by yapzhenyie** [comment]
Sorry for the late reply, I just found out the solution. I will release a new patch update by tomorrow.
