### ISSUE TITLE
{MYSTERY_VAULTS} not parsing in hologram

### ISSUE THREAD

**Issue by Heliosares** [yapzhenyie/GadgetsMenu#942]
Latest Paper, ProtocolLib, and GadgetsMenu Premium.

I have tried with each of the last 4 ProtocolLib builds and it works with none of them.

![image](https://user-images.githubusercontent.com/8331595/208804449-6af86388-58ac-4489-95d9-5429e8b93f56.png)

```[21:12:59 ERROR]: [GadgetsMenu] Unhandled exception number 64 occurred in onPacketSending(PacketEvent) for GadgetsMenu
java.lang.IllegalArgumentException: Unrecognized type class net.minecraft.network.syncher.DataWatcher$b
        at com.comphenix.protocol.wrappers.BukkitConverters$8.getSpecific(BukkitConverters.java:639) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$8.getSpecific(BukkitConverters.java:626) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:43) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters.getSpecificList(BukkitConverters.java:321) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters.access$000(BukkitConverters.java:91) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$3.getSpecific(BukkitConverters.java:365) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$3.getSpecific(BukkitConverters.java:362) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:43) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:274) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:224) ~[ProtocolLib(4).jar:?]
        at com.yapzhenyie.GadgetsMenu.hook.protocollib.packets.WrapperPlayServerEntityMetadata.getEntityMetadata(WrapperPlayServerEntityMetadata.java:96) ~[GadgetsMenu(3).jar:?]
        at com.yapzhenyie.GadgetsMenu.hook.protocollib.packets.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:196) ~[GadgetsMenu(3).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib(4).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib(4).jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:430) ~[?:?]
        at net.minecraft.network.Connection.processQueue(Connection.java:547) ~[?:?]
        at net.minecraft.network.Connection.flushQueue(Connection.java:503) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:398) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.broadcast(ChunkMap.java:1562) ~[?:?]
        at net.minecraft.server.level.ServerEntity.broadcastAndSend(ServerEntity.java:391) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:370) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:203) ~[?:?]
        at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:1267) ~[paper-1.19.3.jar:git-Paper-348]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1278) ~[paper-1.19.3.jar:git-Paper-348]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:818) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:649) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:686) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.3.jar:git-Paper-348]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-348]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-348]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-348]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-348]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by yapzhenyie** [comment]
There're some issues with ProtocolLib in 1.19.3 server. Need to wait for ProtocolLib to release new update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
